{
 "title": "URL Shortener",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "URLs Shortened",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "urls_shortened" }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cache_hits" }
   ]
  },
  {
   "title": "URL Shorten Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "time_to_shorten_ms" }
   ]
  },
  {
   "title": "URL Retrieval Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "time_to_retrieve_ms" }
   ]
  }
 ]
}