apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-deployment
  labels:
    app: short
spec:
  replicas: 1
  selector:
    matchLabels:
      app: short
  template:
    metadata:
      labels:
        app: short
    spec:
      containers:
        - name: short
          image: dddeon/short:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_HOST
              value: "http://ddddddeon.com" # FIXME https://ddddddeon.com
            - name: APP_PORT
              value: "9000"
            - name: PROXY_PORT
              value: "80" #FIXME 443
            - name: MONGO_HOST
              value: mongo # minikube-specific access to host machine
            - name: MONGO_PORT
              value: "27017"
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: PROMETHEUS_HOST
              value: prometheus
            - name: PROMETHEUS_PORT
              value: "9090"

---
apiVersion: v1
kind: Service
metadata:
  name: short-service
spec:
  type: NodePort
  selector:
    app: short
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: short-ingress
spec:
  rules:
    - host: "grafana.ddddddeon.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: short-service
                port:
                  number: 9000
